repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      language: system
      entry: black
      types: [python]
      language_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: flake8
